[workspace]
resolver = "2"
members = ["application", "storage-derive", "binary"]

[workspace.lints.clippy]
arithmetic_side_effects = "deny"

[workspace.dependencies]
#------------------#
# ESP32-HAL crates #
#------------------#
esp-hal = { version = "~1.1.0", features = ["defmt", "esp32c6", "unstable"] }
esp-rtos = { version = "0.3.0", features = [
  "defmt",
  "embassy",
  "esp-alloc",
  "esp-radio",
  "esp32c6",
] }
esp-bootloader-esp-idf = { version = "0.5.0", features = ["defmt", "esp32c6"] }
esp-radio = { version = "0.18.0", features = [
  "ble",
  "coex",
  "esp-alloc",
  "esp32c6",
  "unstable",
  "wifi",
  "defmt"
] }
esp-alloc = { version = "0.10.0", features = ["defmt"] }

# Additional ESP crates
esp-backtrace = { version = "*", features = ["defmt"] }
esp-sync = { version = "0.2.1", features = ["defmt", "esp32c6"] }
esp-storage = { version = "0.9.0", features = ["esp32c6", "embedded-storage", "defmt"]}

#----------------#
# Embassy crates #
#----------------#
embassy-executor = { version = "0.10.0", features = ["nightly"] }
embassy-time = { version = "0.5.1" }
embassy-net = { version = "0.9.1", features = [
  "defmt",
  "dhcpv4",
  "medium-ethernet",
  "tcp",
  "udp",
] }
embassy-time-driver = "0.2.2"
embassy-futures = "0.1.2"
embassy-sync = "0.8.0"
embassy-embedded-hal = "0.6.0"

#----------------------#
# Embedded-hal crates  #
#----------------------#
embedded-io = { version = "0.7.1", features = ["defmt"] }
embedded-io-async = { version = "0.7.0", features = ["defmt"] }
embedded-hal-async = "1.0.0"
embedded-hal-bus = "0.3.0"
embedded-hal = "1.0.0"
embedded-storage-async = "0.4.1"

#---------------------#
# Connectivity crates #
#---------------------#
# for more networking protocol support see https://crates.io/crates/edge-net
bt-hci = "0.9.0"
smoltcp = { version = "0.13.0", default-features = false, features = [
  "medium-ethernet",
  "multicast",
  "proto-dhcpv4",
  "proto-dns",
  "proto-ipv4",
  "socket-dns",
  "socket-icmp",
  "socket-raw",
  "socket-tcp",
  "socket-udp",
] }

#----------------------#
# Defmt logging crates #
#----------------------#
defmt = "1.1.1"
panic-rtt-target = { version = "0.2.0", features = ["defmt"] }
rtt-target = { version = "0.6.2", features = ["defmt"] }

#---------#
# Drivers #
#---------#

# Display 
display-interface = "0.5.0"
embedded-graphics = "0.8.2"
ssd1306 = { version = "0.10.0", features = ["async", "graphics"] }

# RTC
pcf85063a = "0.1.1"

#----------------#
# Utility crates #
#----------------#

critical-section = "1.2.0"
static_cell = { version = "2.1.1", features = ["nightly"] }
fixed = { version = "=1.20.0", features = ["serde", "num-traits"] }
enumset = "1.1.14"
modular-bitfield = "0.13.1"
strum = { version = "0.28.0", default-features = false }
strum_macros = { version = "0.28.0", default-features = false }
heapless = { version = "0.9.3", features = ["portable-atomic"] }
libm = "0.2.16"
postcard = { version = "1.1.3", features = ["heapless"] }
serde = { version = "1.0.229", default-features = false }
sequential-storage = { version = "8.0.1", features = ["heapless", "postcard", "alloc", "defmt"] }

#--------------------#
# Slint dependencies #
#--------------------#

[workspace.dependencies.mcu-board-support]
version = "1.17.1"
default-features = false
git = "https://github.com/slint-ui/slint"
rev = "cf62c97"

[workspace.dependencies.i-slint-core]
version = "1.17.1"
default-features = false
features = ["libm", "unsafe-single-threaded"]
git = "https://github.com/slint-ui/slint"
rev = "cf62c97"

[workspace.dependencies.slint]
version = "1.17.1"
default-features = false
features = ["compat-1-2", "unsafe-single-threaded", "libm", "renderer-software"]
git = "https://github.com/slint-ui/slint"
rev = "cf62c97"

[workspace.dependencies.i-slint-renderer-software]
version = "1.17.1"
default-features = false
features = [ "experimental", "libm", "path" ]
git = "https://github.com/slint-ui/slint"
rev = "cf62c97"

[workspace.dependencies.slint-build]
version = "1.17.1"
git = "https://github.com/slint-ui/slint"
rev = "cf62c97"

# Patch for the updated esp pacs created by me
[patch."https://github.com/esp-rs/esp-pacs"]
esp32c6 = { git = "https://github.com/Alex3404/esp-pacs-mcpwm", rev = "e78b9efbb166ee2197a5b67144044b137c429e55" }

# Patch for the updated esp hal created by me
[patch.crates-io]
esp-alloc = { git = "https://github.com/esp-rs/esp-hal", rev = "5161ec77b28aa4b84cc834c4a468115d3535c975" }
esp-backtrace = { git = "https://github.com/esp-rs/esp-hal", rev = "5161ec77b28aa4b84cc834c4a468115d3535c975" }
esp-bootloader-esp-idf = { git = "https://github.com/esp-rs/esp-hal", rev = "5161ec77b28aa4b84cc834c4a468115d3535c975" }
esp-hal = { git = "https://github.com/esp-rs/esp-hal", rev = "5161ec77b28aa4b84cc834c4a468115d3535c975" }
esp-radio = { git = "https://github.com/esp-rs/esp-hal", rev = "5161ec77b28aa4b84cc834c4a468115d3535c975" }
esp-rtos = { git = "https://github.com/esp-rs/esp-hal", rev = "5161ec77b28aa4b84cc834c4a468115d3535c975" }
esp-storage = { git = "https://github.com/esp-rs/esp-hal", rev = "5161ec77b28aa4b84cc834c4a468115d3535c975" }

#--------------------#

# For fine tuning these settings, please refer to https://doc.rust-lang.org/cargo/reference/profiles.html
[profile.dev]
# The default debug profile is too slow and too big for resource-constrained devices.
# Always build with some optimizations enabled.
opt-level = "s"

[profile.release]
codegen-units = 1     # LLVM can perform better optimizations using a single thread
debug         = 2     # prefer slower builds but better debugging experience
lto           = 'fat'
opt-level     = 's'
